name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish PowerShell Gallery
      shell: pwsh
      run: |
        Publish-Module -Path .\PSSryliusWrite -NuGetApiKey ${{ secrets.PS_NUGET_KEY }} -Verbose
