# Srylius :: Action name
name    : Publish PowerShell Module

# Srylius :: Action required to take action
on      :
  # Srylius :: Make it work only when version is released
  release :
    types : [published]

# Srylius :: Jobs to be done during the action 
jobs    :
  # Srylius :: Publish the module in the PowerShell Gallery
  publish-to-gallery :
    # Srylius :: Target operating system
    runs-on : windows-latest
    
    # Srylius :: Steps to be taken
    steps   :
    - uses    : actions/checkout@v2
    - name    : Publish PowerShell Module
      shell   : pwsh
      run     : |
        Publish-Module -Path .\PSSryliusWrite -NuGetApiKey ${{ secrets.PS_NUGET_KEY }} -Verbose
